In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
df=pd.read_csv(r'C:\Users\user\Downloads\Churn_Modelling.csv')

In [3]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [6]:
df['CustomerId'].nunique()

10000

In [7]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

# find the customer with credit score between 700 to 850

In [8]:
def credit_score_filter(df):
    df_filter=df[(df['CreditScore']> 700) & (df['CreditScore'] <= 850)]
    x=len(df_filter)
    y=print('No of score more than 700:',x)
    return y,df_filter

In [9]:
#credit_score_filter(df)

# find the customer ID that bought num of products:3

In [10]:
def customer_purchase(df):
    df_filter=df[(df['NumOfProducts'])== 3]
    x=len(df_filter)
    y=print('No of customer with no of prodcuts-3:',x)
    customer_detail=df_filter[['CustomerId','CreditScore','NumOfProducts']]
    return y,customer_detail

In [11]:
customer_purchase(df)

No of customer with no of prodcuts-3: 266

(None,
       CustomerId  CreditScore  NumOfProducts
 2       15619304          502              3
 30      15589475          591              3
 88      15622897          646              3
 90      15757535          647              3
 227     15676895          547              3
 ...          ...          ...            ...
 9737    15741197          710              3
 9747    15775761          610              3
 9800    15640507          762              3
 9877    15572182          505              3
 9895    15796764          684              3

 [266 rows x 3 columns])

# list of customer ID who left the bank(exited=0)and who not left the bank(exited=1)

In [12]:
def Exited_filter(df):
    Exited_no=df[(df['Exited'] == 1)]
    Exited_no_ID_list=list(Exited_no['CustomerId'])
    Exited_yes=df[(df['Exited'] == 0)]
    Exited_yes_ID_list=list(Exited_yes['CustomerId'])
    return Exited_no_ID_list, Exited_yes_ID_list

In [13]:
Exited_filter(df)

([15634602,
  15619304,
  15574012,
  15656148,
  15737452,
  15699309,
  15589475,
  15794171,
  15738148,
  15755196,
  15602280,
  15771573,
  15702298,
  15569590,
  15623944,
  15703793,
  15663706,
  15762418,
  15622897,
  15757535,
  15804919,
  15613854,
  15744689,
  15609618,
  15661670,
  15627360,
  15671137,
  15782688,
  15594408,
  15640905,
  15713483,
  15612350,
  15759618,
  15679145,
  15658929,
  15724623,
  15574692,
  15651022,
  15625426,
  15719377,
  15726931,
  15600974,
  15727868,
  15755262,
  15684181,
  15723488,
  15659366,
  15774854,
  15733247,
  15568748,
  15676895,
  15637753,
  15772896,
  15764866,
  15794056,
  15596175,
  15797219,
  15772423,
  15717398,
  15619955,
  15694456,
  15782210,
  15643024,
  15590241,
  15684173,
  15594898,
  15773972,
  15662736,
  15694408,
  15736008,
  15728669,
  15697441,
  15636624,
  15807923,
  15745844,
  15661629,
  15696674,
  15583456,
  15629677,
  15573456,
  15684548,
  15646372,
  15578045,
  15801559,
  15720559,
  15810418,
  15674551,
  15806467,
  15597602,
  15595039,
  15787470,
  15694860,
  15707362,
  15773792,
  15593782,
  15683625,
  15591986,
  15676519,
  15613772,
  15725679,
  15585865,
  15677020,
  15714485,
  15682048,
  15752081,
  15775912,
  15671256,
  15653849,
  15776780,
  15794142,
  15762729,
  15705953,
  15802593,
  15657284,
  15775318,
  15634844,
  15665956,
  15651674,
  15730076,
  15607312,
  15737741,
  15803689,
  15718057,
  15722010,
  15591047,
  15788291,
  15637476,
  15683503,
  15592387,
  15745295,
  15766575,
  15712403,
  15811762,
  15738181,
  15784844,
  15640078,
  15698786,
  15569807,
  15664610,
  15715142,
  15600337,
  15579334,
  15802741,
  15727299,
  15620204,
  15580148,
  15807609,
  15721658,
  15578761,
  15612525,
  15744607,
  15612966,
  15641675,
  15582741,
  15637876,
  15672056,
  15677921,
  15685329,
  15584091,
  15789158,
  15712551,
  15628936,
  15571221,
  15756026,
  15775306,
  15806438,
  15757811,
  15585888,
  15707567,
  15672012,
  15794048,
  15693864,
  15809087,
  15807663,
  15809100,
  15756804,
  15646810,
  15692750,
  15585362,
  15571928,
  15743007,
  15772781,
  15669987,
  15654700,
  15642041,
  15794580,
  15675964,
  15724848,
  15792328,
  15743411,
  15753337,
  15737795,
  15613630,
  15804586,
  15745324,
  15741336,
  15620981,
  15660429,
  15731815,
  15580956,
  15570060,
  15807008,
  15613749,
  15681206,
  15701301,
  15701602,
  15569050,
  15799811,
  15686936,
  15602010,
  15654673,
  15593969,
  15644200,
  15793949,
  15705860,
  15706534,
  15631189,
  15692744,
  15688963,
  15680303,
  15628674,
  15648075,
  15663438,
  15646513,
  15708063,
  15585198,
  15689081,
  15813168,
  15660316,
  15592229,
  15798424,
  15648800,
  15626147,
  15592583,
  15789955,
  15596800,
  15627305,
  15685309,
  15566251,
  15694821,
  15669899,
  15690007,
  15719348,
  15781802,
  15640454,
  15588670,
  15782454,
  15755638,
  15719302,
  15791279,
  15589572,
  15779947,
  15651052,
  15658969,
  15813590,
  15674148,
  15625080,
  15730038,
  15812272,
  15607537,
  15658052,
  15814930,
  15610383,
  15743532,
  15662291,
  15612064,
  15690182,
  15779182,
  15688880,
  15683930,
  15800434,
  15709117,
  15596181,
  15644833,
  15720702,
  15665077,
  15629244,
  15574331,
  15645572,
  15576683,
  15645511,
  15609824,
  15691104,
  15635435,
  15596552,
  15683403,
  15689514,
  15627232,
  15722902,
  15771942,
  15587233,
  15714466,
  15690647,
  15775295,
  15684196,
  15787835,
  15748797,
  15754796,
  15628947,
  15797276,
  15612494,
  15710164,
  15596671,
  15799966,
  15574068,
  15796334,
  15598751,
  15697311,
  15585367,
  15676242,
  15774882,
  15608653,
  15571778,
  15566211,
  15814846,
  15670374,
  15630725,
  15700212,
  15716491,
  15625824,
  15634891,
  15744517,
  15590146,
  15762277,
  15798975,
  15738267,
  15786800,
  15782736,
  15584364,
  15709994,
  15706815,
  15600991,
  15683124,
  15670823,
  15607133,
  15725141,
  15730394,
  15647842,
  15751158,
  15781553,
  15649121,
  15777797,
  15588248,
  15595303,
  15634950,
  15685372,
  15651533,
  15585067,
  15633233,
  15752342,
  15663441,
  15579706,
  15716994,
  15675896,
  15658057,
  15713826,
  15700854,
  15605279,
  15684269,
  15578603,
  15765694,
  15568963,
  15703820,
  15778410,
  15704763,
  15701121,
  15796313,
  15689980,
  15642002,
  15603846,
  15753549,
  15764170,
  15610446,
  15605037,
  15711219,
  15678727,
  15740104,
  15605275,
  15804394,
  15619343,
  15758813,
  15589076,
  15758845,
  15711455,
  15570601,
  15690925,
  15726494,
  15664754,
  15643630,
  15629078,
  15576644,
  15812198,
  15699772,
  15739858,
  15638355,
  15805637,
  15629575,
  15716609,
  15652693,
  15659651,
  15607347,
  15615456,
  15589793,
  15779176,
  15605286,
  15674922,
  15692416,
  15738318,
  15772243,
  15585901,
  15627876,
  15758606,
  15657107,
  15787189,
  15666055,
  15755678,
  15725835,
  15727384,
  15732917,
  15633043,
  15606613,
  15658716,
  15678146,
  15710743,
  15723008,
  15797160,
  15610686,
  15577078,
  15571305,
  15629338,
  15750684,
  15805303,
  15780254,
  15815626,
  15813412,
  15668669,
  15687658,
  15757408,
  15769216,
  15659931,
  15795990,
  15718893,
  15774857,
  15651554,
  15603851,
  15599722,
  15704284,
  15765518,
  15758372,
  15648794,
  15588614,
  15630698,
  15694200,
  15721426,
  15805260,
  15738605,
  15762169,
  15609998,
  15583548,
  15735246,
  15791700,
  15809826,
  15803749,
  15736069,
  15713655,
  15633930,
  15712849,
  15639077,
  15648577,
  15633112,
  15780038,
  15578799,
  15586264,
  15629323,
  15777553,
  15622217,
  15570835,
  15808044,
  15684951,
  15783615,
  15789097,
  15801265,
  15664543,
  15582714,
  15621210,
  15724223,
  15624388,
  15581440,
  15654390,
  15595728,
  15642345,
  15706163,
  15746708,
  15787907,
  15646764,
  15678284,
  15726791,
  15710366,
  15791053,
  15682600,
  15708212,
  15578297,
  15774151,
  15778395,
  15657342,
  15672374,
  15809286,
  15579130,
  15806027,
  15603914,
  15661821,
  15689351,
  15782247,
  15769064,
  15613189,
  15792525,
  15586976,
  15567980,
  15636089,
  15727490,
  15756920,
  15726403,
  15704442,
  15630617,
  15679249,
  15693199,
  15760294,
  15778155,
  15666548,
  15634974,
  15689341,
  15744327,
  15759436,
  15751561,
  15726490,
  15598086,
  15578809,
  15752026,
  15569571,
  15769703,
  15679770,
  15791102,
  15755178,
  15617197,
  15631240,
  15732270,
  15711834,
  15672144,
  15775905,
  15688691,
  15592736,
  15597896,
  15731790,
  15787318,
  15744582,
  15640846,
  15602735,
  15800062,
  15775891,
  15711789,
  15680278,
  15581036,
  15687162,
  15759874,
  15815490,
  15679410,
  15688409,
  15742272,
  15635660,
  15582325,
  15760446,
  15641994,
  15636999,
  15639946,
  15729954,
  15627352,
  15809178,
  15806688,
  15576824,
  15592816,
  15662098,
  15658889,
  15753332,
  15767474,
  15626787,
  15566708,
  15730433,
  15782468,
  15776233,
  15641416,
  15771417,
  15585100,
  15700487,
  15747503,
  15597930,
  15723299,
  15618936,
  15787529,
  15600934,
  15785782,
  15812513,
  15678572,
  15776454,
  15648489,
  15813067,
  15707968,
  15671591,
  15669411,
  15789425,
  15624510,
  15668575,
  15628972,
  15617482,
  15704583,
  15621083,
  15649487,
  15581198,
  15724858,
  15690188,
  15591915,
  15776348,
  15671655,
  15789109,
  15605000,
  15577178,
  15595324,
  15595228,
  15651983,
  15655123,
  15682268,
  15684801,
  15636428,
  15720943,
  15697997,
  15619653,
  15800061,
  15687491,
  15779862,
  15699247,
  15570932,
  15609653,
  15759066,
  15814816,
  15571059,
  15779581,
  15745083,
  15794566,
  15697424,
  15735878,
  15707596,
  15622478,
  15636023,
  15663161,
  15795224,
  15721007,
  15813113,
  15772073,
  15701537,
  15769596,
  15775590,
  15730688,
  15810075,
  15724161,
  15569641,
  15801336,
  15746203,
  15583137,
  15680752,
  15791373,
  15589449,
  15764604,
  15750447,
  15631070,
  15761950,
  15725794,
  15678201,
  15603942,
  15733973,
  15596761,
  15747097,
  15713463,
  15589715,
  15664907,
  15588080,
  15717560,
  15768151,
  15579212,
  15587419,
  15750335,
  15778368,
  15768072,
  15654456,
  15807525,
  15611430,
  15793890,
  15646091,
  15596984,
  15715622,
  15627220,
  15706071,
  15801904,
  15784320,
  15628767,
  15758116,
  15575119,
  15799626,
  15651352,
  15647385,
  15631305,
  15603465,
  15750638,
  15764431,
  15648881,
  15749905,
  15625175,
  15643967,
  15733234,
  15721582,
  15628219,
  15765982,
  15724863,
  15633352,
  15593736,
  15710689,
  15674678,
  15745605,
  15606755,
  15612092,
  15722965,
  15789974,
  15713370,
  15791216,
  15627840,
  15806956,
  15807993,
  15728456,
  15809137,
  15588944,
  15660505,
  15594878,
  15569248,
  15623712,
  15653251,
  15755077,
  15808557,
  15761023,
  15801218,
  15641359,
  15647725,
  15626612,
  15629094,
  15651823,
  15727353,
  15733777,
  15723263,
  15803121,
  15761670,
  15706005,
  15711618,
  15773221,
  15628886,
  15573599,
  15747208,
  15772528,
  15711716,
  15639357,
  15738907,
  15663446,
  15750867,
  15634968,
  15809320,
  15793049,
  15607263,
  15610900,
  15691703,
  15759284,
  15661903,
  15664668,
  15602731,
  15586133,
  15666270,
  15727197,
  15722246,
  15609704,
  15768451,
  15812616,
  15729489,
  15640409,
  15577999,
  15703541,
  15608344,
  15768367,
  15568573,
  15689598,
  15635396,
  15678944,
  15718507,
  15804709,
  15582910,
  15773868,
  15691785,
  15685290,
  15680449,
  15599860,
  15728224,
  15644174,
  15756751,
  15584037,
  15669887,
  15651264,
  15724251,
  15718289,
  15654733,
  15602797,
  15778154,
  15806230,
  15662884,
  15750778,
  15677804,
  15615126,
  15753847,
  15757541,
  15618255,
  15750156,
  15720305,
  15698716,
  15732266,
  15640258,
  15743871,
  15626008,
  15648362,
  15723717,
  15659736,
  15603170,
  15619972,
  15756610,
  15663164,
  15714981,
  15743673,
  15720071,
  15783030,
  15627665,
  15814092,
  15650442,
  15601659,
  15737071,
  15792064,
  15677052,
  15653776,
  15597914,
  15678034,
  15697100,
  15606641,
  15569079,
  15640034,
  15807563,
  15684461,
  15734762,
  15800083,
  15689886,
  15676404,
  15812262,
  15669301,
  15798470,
  15676571,
  15643865,
  15647008,
  15608406,
  15625545,
  15810829,
  15757952,
  15609623,
  15569098,
  15664001,
  15654562,
  15693376,
  15577587,
  15635141,
  15747168,
  15796910,
  15707674,
  15565706,
  15720929,
  15729201,
  15615207,
  15574213,
  15583840,
  15782418,
  15711314,
  15627847,
  15588090,
  15735270,
  15746553,
  15622518,
  15664555,
  15761294,
  15673984,
  15709941,
  15690021,
  15740527,
  15657529,
  15800287,
  15616454,
  15778149,
  15791867,
  15675380,
  15775294,
  15654000,
  15719991,
  15720687,
  15720774,
  15579566,
  15771543,
  15810460,
  15771742,
  15772412,
  15654577,
  15584536,
  15585853,
  15645271,
  15623107,
  15592000,
  15675854,
  15714391,
  15596455,
  15696301,
  15812241,
  15674328,
  15572547,
  15567063,
  15720637,
  15616859,
  15781598,
  15740345,
  15686463,
  15648967,
  15779522,
  15716381,
  15704788,
  15641312,
  15676937,
  15778975,
  15692443,
  15593795,
  15642824,
  15774192,
  15758901,
  15632118,
  15568006,
  15751748,
  15812210,
  15605826,
  15570087,
  15607275,
  15635034,
  15692929,
  15672152,
  15673372,
  15587611,
  15715673,
  15733261,
  15668248,
  15694376,
  15711028,
  15658475,
  15782360,
  15677105,
  15784958,
  15734524,
  15614103,
  15649292,
  15622532,
  15710543,
  15687153,
  15583353,
  15696373,
  15672594,
  15751392,
  15579617,
  15593976,
  15596870,
  15751491,
  15808674,
  15791780,
  15607314,
  15737832,
  15680706,
  15748597,
  15618774,
  15583580,
  15788556,
  15576550,
  15653937,
  15591740,
  15644361,
  15605020,
  15582849,
  15655410,
  15759067,
  15763256,
  ...],
 [15647311,
  15701354,
  15737888,
  15592531,
  15792365,
  15592389,
  15767821,
  15737173,
  15632264,
  15691483,
  15600882,
  15643966,
  15788218,
  15661507,
  15568982,
  15577657,
  15597945,
  15725737,
  15625047,
  15738191,
  15736816,
  15700772,
  15728693,
  15656300,
  15706552,
  15750181,
  15659428,
  15732963,
  15788448,
  15729599,
  15717426,
  15585768,
  15619360,
  15687946,
  15684171,
  15754849,
  15766205,
  15771873,
  15616550,
  15768193,
  15683553,
  15760861,
  15630053,
  15647091,
  15804771,
  15651280,
  15773469,
  15702014,
  15751208,
  15592461,
  15789484,
  15696061,
  15641582,
  15638424,
  15755648,
  15620344,
  15812518,
  15779052,
  15770811,
  15780961,
  15614049,
  15662085,
  15575185,
  15803136,
  15706021,
  15641732,
  15701164,
  15738751,
  15805254,
  15625759,
  15767954,
  15731511,
  15809248,
  15640635,
  15676966,
  15699461,
  15738721,
  15693683,
  15604348,
  15633059,
  15808582,
  15743192,
  15580146,
  15776605,
  15599195,
  15812878,
  15602312,
  15803526,
  15665790,
  15715951,
  15591100,
  15675522,
  15705512,
  15698028,
  15600781,
  15682472,
  15580203,
  15690673,
  15760085,
  15779659,
  15575492,
  15591607,
  15740404,
  15718369,
  15677871,
  15642004,
  15712543,
  15584518,
  15802381,
  15610156,
  15698932,
  15724944,
  15628145,
  15800703,
  15705707,
  15754105,
  15703264,
  15794413,
  15650237,
  15811589,
  15689044,
  15709368,
  15655007,
  15623595,
  15589975,
  15804017,
  15692132,
  15641122,
  15630910,
  15680772,
  15585388,
  15588537,
  15611325,
  15587562,
  15613172,
  15586310,
  15625524,
  15755209,
  15645248,
  15790355,
  15762615,
  15716334,
  15789669,
  15621075,
  15810845,
  15654506,
  15771977,
  15708710,
  15726676,
  15587421,
  15771086,
  15756850,
  15702741,
  15679200,
  15594815,
  15635905,
  15777892,
  15656176,
  15811127,
  15604482,
  15622911,
  15627801,
  15773039,
  15679531,
  15612087,
  15752047,
  15624592,
  15573152,
  15594917,
  15785542,
  15680920,
  15786308,
  15725311,
  15787155,
  15727829,
  15699029,
  15774393,
  15605461,
  15808473,
  15627000,
  15787174,
  15723886,
  15704769,
  15711540,
  15795149,
  15812009,
  15651001,
  15813844,
  15576269,
  15685500,
  15599792,
  15657566,
  15628112,
  15753754,
  15793726,
  15694717,
  15665834,
  15765297,
  15636684,
  15592979,
  15750803,
  15607178,
  15713853,
  15673481,
  15686776,
  15673693,
  15700696,
  15813163,
  15653857,
  15777076,
  15799217,
  15787071,
  15796505,
  15725166,
  15800116,
  15758685,
  15767339,
  15683562,
  15668893,
  15669169,
  15699389,
  15708608,
  15626144,
  15573112,
  15790678,
  15727556,
  15697307,
  15652266,
  15607098,
  15655774,
  15785819,
  15723654,
  15774510,
  15650068,
  15811490,
  15803976,
  15682541,
  15695699,
  15624188,
  15812191,
  15636673,
  15660211,
  15746726,
  15712287,
  15702919,
  15674398,
  15797960,
  15631868,
  15581539,
  15666252,
  15677512,
  15626114,
  15810834,
  15678910,
  15585215,
  15682757,
  15736601,
  15601848,
  15669064,
  15624528,
  15598493,
  15601274,
  15702669,
  15742668,
  15740476,
  15648064,
  15786170,
  15681081,
  15684484,
  15785869,
  15763859,
  15658935,
  15747358,
  15735203,
  15576256,
  15659420,
  15593365,
  15777352,
  15812007,
  15625461,
  15739438,
  15611759,
  15633950,
  15592386,
  15803716,
  15706365,
  15745088,
  15676715,
  15613085,
  15633537,
  15594720,
  15684042,
  15583303,
  15611579,
  15774696,
  15694506,
  15688074,
  15759537,
  15758449,
  15667871,
  15677371,
  15713578,
  15591509,
  15568240,
  15622993,
  15689294,
  15720910,
  15721181,
  15776433,
  15748936,
  15717225,
  15685226,
  15785611,
  15620505,
  15807432,
  15584766,
  15612187,
  15762218,
  15690452,
  15747795,
  15781589,
  15732674,
  15642291,
  15692761,
  15745354,
  15701376,
  15691625,
  15566594,
  15760431,
  15686302,
  15810432,
  15809616,
  15695632,
  15659843,
  15615624,
  15716186,
  15622834,
  15566111,
  15784597,
  15652883,
  15806964,
  15576313,
  15743040,
  15705521,
  15799384,
  15581197,
  15693737,
  15624623,
  15783501,
  15690134,
  15782735,
  15611088,
  15672145,
  15732628,
  15803406,
  15730460,
  15644572,
  15658169,
  15794396,
  15785798,
  15710825,
  15668444,
  15726631,
  15733797,
  15747960,
  15634632,
  15662976,
  15732778,
  15718443,
  15670039,
  15613786,
  15726032,
  15663252,
  15633283,
  15749167,
  15759298,
  15635367,
  15681705,
  15603156,
  15798888,
  15809722,
  15677538,
  15797736,
  15695585,
  15744398,
  15750658,
  15578186,
  15637954,
  15758639,
  15731744,
  15807709,
  15714689,
  15699005,
  15624170,
  15804256,
  15662403,
  15733616,
  15591995,
  15727688,
  15715941,
  15730059,
  15715527,
  15576623,
  15805565,
  15677307,
  15773890,
  15598883,
  15568506,
  15761043,
  15782236,
  15593601,
  15746902,
  15781307,
  15745417,
  15653547,
  15595766,
  15742358,
  15763274,
  15786063,
  15600258,
  15573318,
  15694272,
  15736112,
  15749851,
  15663478,
  15592300,
  15567832,
  15592846,
  15739803,
  15667896,
  15626578,
  15776223,
  15615457,
  15708916,
  15720187,
  15595440,
  15600651,
  15750141,
  15763063,
  15709324,
  15711309,
  15705515,
  15717046,
  15571816,
  15670080,
  15800440,
  15665678,
  15788126,
  15811773,
  15689614,
  15795564,
  15706647,
  15728505,
  15622003,
  15644753,
  15653620,
  15761986,
  15633922,
  15734674,
  15658032,
  15692671,
  15576352,
  15753719,
  15680998,
  15614782,
  15604044,
  15679587,
  15775153,
  15603925,
  15680970,
  15697183,
  15567446,
  15714939,
  15645569,
  15782569,
  15609286,
  15814035,
  15661249,
  15629117,
  15607170,
  15586585,
  15686611,
  15603203,
  15619857,
  15805062,
  15660271,
  15719352,
  15594594,
  15646161,
  15682585,
  15603134,
  15636444,
  15773456,
  15745307,
  15604119,
  15626900,
  15605447,
  15589030,
  15692463,
  15718673,
  15724282,
  15633648,
  15603323,
  15583725,
  15588350,
  15798398,
  15580684,
  15809663,
  15730830,
  15805112,
  15633064,
  15703119,
  15730447,
  15813850,
  15711889,
  15751710,
  15692926,
  15813741,
  15698474,
  15568595,
  15603065,
  15592937,
  15699637,
  15667215,
  15788659,
  15763218,
  15645772,
  15725511,
  15575024,
  15640825,
  15662397,
  15576368,
  15674991,
  15721024,
  15745621,
  15642394,
  15754605,
  15607040,
  15810978,
  15668886,
  15780804,
  15613880,
  15775238,
  15786905,
  15747867,
  15801277,
  15720649,
  15589493,
  15688251,
  15665238,
  15740900,
  15681068,
  15748625,
  15669516,
  15736534,
  15803457,
  15659098,
  15603436,
  15566292,
  15808621,
  15776231,
  15773809,
  15649423,
  15734886,
  15722548,
  15650288,
  15629448,
  15716164,
  15578977,
  15677369,
  15804072,
  15696859,
  15653780,
  15736879,
  15571973,
  15626742,
  15672692,
  15673570,
  15767432,
  15654238,
  15812750,
  15790757,
  15723873,
  15784209,
  15794278,
  15766741,
  15661036,
  15705639,
  15637414,
  15716835,
  15696231,
  15670755,
  15640059,
  15787619,
  15587535,
  15813034,
  15698839,
  15790314,
  15634245,
  15677305,
  15661526,
  15685997,
  15660101,
  15637979,
  15815364,
  15647099,
  15625944,
  15583212,
  15622750,
  15812351,
  15810864,
  15724296,
  15640442,
  15639314,
  15685320,
  15752137,
  15797227,
  15769974,
  15737051,
  15585595,
  15654060,
  15745196,
  15660155,
  15605284,
  15694366,
  15600739,
  15653253,
  15763431,
  15643696,
  15707473,
  15769504,
  15776807,
  15686870,
  15668747,
  15766908,
  15570134,
  15567367,
  15747542,
  15762238,
  15681554,
  15712825,
  15640280,
  15613319,
  15798906,
  15708917,
  15778463,
  15699430,
  15649992,
  15578980,
  15641655,
  15619708,
  15734565,
  15591969,
  15747807,
  15596939,
  15716155,
  15765311,
  15603830,
  15660602,
  15660535,
  15666633,
  15596914,
  15639788,
  15695846,
  15726234,
  15797964,

In [14]:
type(df['Surname'])

pandas.core.series.Series

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

# filter surname startswith

In [19]:
def surname_filter(df):
    surname_startswith ="H"
    bool_series= df["Surname"].str.startswith(surname_startswith)
    return df[bool_series]

In [20]:
surname_filter(df)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9897,9898,15810563,Ho,678,Spain,Female,61,8,0.00,2,1,1,159938.82,0
9901,9902,15802909,Hu,706,Germany,Female,56,3,139603.22,1,1,1,86383.61,0
9914,9915,15568876,Hughes,496,France,Female,34,1,102723.35,2,1,0,180844.81,0
9951,9952,15763874,Ho,635,Spain,Male,46,8,0.00,2,1,1,60739.16,0
9969,9970,15806360,Hou,609,France,Male,41,6,0.00,1,0,1,112585.19,0